### ISSUE TITLE
Yandex "Read more" link/button not working

### ISSUE THREAD

**Issue by roytam1** [wicknix/Arctic-Fox#25]
forwarding a bug report from K-Meleon Goanna:
http://kmeleonbrowser.org/forum/read.php?3,148928,148928

> one cannot expand 'Read more' link in main list of search results like this: (click doesn't work) 
> `https://yandex.com/search/?text=elon&lr=102571`

regression seems starting from https://github.com/rmottola/Arctic-Fox/commit/c8ada5454 (I can't sure which is exact commit since I did git squash merge in a range of commits: https://github.com/roytam1/palemoon27/commit/4573c3bc0f8ee98a6f45447d84d93b3046df2359 )

EDIT: it seems that bug 1134280 patches causing this issue

cc @rmottola

**Comment by roytam1** [comment]
it seems that bug 1134280 patches causing this issue

**Comment by rmottola** [comment]
I rechecked all patches against original patches. While there are some differences due to different source files, I could not spot any error, although, due to size, something could have slipped through.
Did you include 1356843 by chance?

I had those patches since weeks and couldn't detect issues, do you have a way to reproduce the issue on a different site I can't access? I don't use yandex mail. A testcase would be best (this would lead us to the point that knowing how to execute mochitests and others tests would be good)

**Comment by roytam1** [comment]
> Did you include 1356843 by chance?

having it or not doesn't affect the result.

> A testcase would be best

I DO want to have minimal test case as yandex search page is too complicated.

**Comment by roytam1** [comment]
FYI: dom/ commits after this bug: https://github.com/mozilla/gecko-dev/commits/04bd6d2255ca35057a7f8d18fc03e908d02f6907?after=04bd6d2255ca35057a7f8d18fc03e908d02f6907+454&path[]=dom

**Comment by roytam1** [comment]
so the fix seems to be happen here?
https://github.com/mozilla/gecko-dev/commit/de4b4e39c8b7908032c219f29bb12869913d05c3#diff-80038c946ec8d0f3cae6f06cfd5b0eb7R1801

**Comment by roytam1** [comment]
fix confirmed in my side: https://github.com/roytam1/palemoon27/commit/6a3c759b17f527b4db6427e4ad2c7b03533f95ce

**Comment by rmottola** [comment]
Applied the same fix on my side.
