### ISSUE TITLE
Java?

### ISSUE THREAD

**Issue by Chris230291** [wicknix/Arctic-Fox#64]
Hi. Does anyone know if its possible to get Java working on OS X 10.7 with Arctic Fox?

Thanks.

**Comment by wicknix** [comment]
Sorry for the late reply. Seems my email notifications aren't functioning. Anyway, Java on 10.6/10.7 is quite old and insecure and is more than likely blocked. Since AF is based on PM, this post was all i could find in their forum archive related to java. It may help, or it may not.  https://forum.palemoon.org/viewtopic.php?t=639
